### PR TITLE
Update THANKS

### PR DESCRIPTION
**Pull request by shades2**
Add Mike Benjamin

Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by sebres** [comment]
Neither I know what `ssh_brute_blocker` is, nor that it has lead to creation of fail2ban.

Related to linkedit he designed ssh_brute_blocker security scripts in 2004, fail2ban seems to have initial commit also in 2004, but this commit means "New repository initialized by cvs2svn", so fail2ban existed for a while as CVS-repository (I don't really know when exactly it gets started).

@fail2ban/owners, @lostcontrol Any thoughts?

By the way, the list of contributors is sorted alphabetically.

**Comment by lostcontrol** [comment]
I have never heard of `ssh_brute_blocker` before and don't remember Mike Benjamin at all. The inspiration does definitely not come from there. You can watch [this part of a presentation](https://youtu.be/L17vXppH0Cs?t=490) I did a few years ago (sorry, French but slides in English). The only inspiration I had back in 2004 was 1. script kiddies trying to log into my home server and 2. my wish to learn Python.

**Comment by shades2** [comment]
So Cyril, after failing to ever respond to me directly, you're saying you
weren't on, or using that seclists.org forum when I posted my code?

I think you've chosen not to remember, and not to
properly accredit someone.I'll check with Wietse Venema if he was aware of
the existence of fail2ban before my post there. Should clear it up.

**Comment by lostcontrol** [comment]
> So Cyril, after failing to ever respond to me directly, you're saying you weren't on, or using that seclists.org forum when I posted my code? I think you've chosen not to remember, and not to properly accredit someone.I'll check with Wietse Venema if he was aware of the existence of fail2ban before my post there. Should clear it up.

Sorry Michael if I didn't respond to you. I rarely read my fail2ban's emails for many years and I actually stumbled upon this discussion here "by accident". Honestly, I don't remember ever posting to seclists.org or even knowing this forum. But this was almost 20 years ago so it's a bit hard to be 100% sure. I didn't find anything related to me on seclists.org!? Who is Wietse Venema and what does he have to do with all of this?

Of course, I received a lot of contributions from people who wrote scripts and configuration files for fail2ban. Some of them are in the THANKS file but probably not all. If you feel like you should be there, show us your contribution to the project. Not just a supposed inspiration. Back in 2004, I remember [denyhosts](https://denyhosts.sourceforge.net) had (and still has) the same purposes as fail2ban (yet, fail2ban was more generic whereas denyhosts concentrated on SSH). Nobody from that project ever complained about fail2ban being "inspired" by it. And again, I never started fail2ban as a copycat project of anything. Just wanted to solve my own issues with script kiddies while learning Python.

**Pull request closed without merging**
