### PR TITLE
Update sshd.conf

### PR DESCRIPTION
**Pull request by flixman**
Added rule to prevent people from just dropping at preauth.

Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by rnestler** [comment]
> Or do you really see only this (so 1 message per session without others):

At least on my system (Debian Buster) I have log messages that are either in the mentioned tripples or just 1 message without others:
```
Jan  9 13:16:32  sshd[11452]: Connection closed by 46.101.89.150 port 57490 [preauth]                                                                                  
Jan  9 13:18:29  sshd[11463]: Invalid user pim from 49.233.183.155 port 35330
Jan  9 13:18:29  sshd[11463]: Received disconnect from 49.233.183.155 port 35330:11: Bye Bye [preauth]                                                                 
Jan  9 13:18:29  sshd[11463]: Disconnected from invalid user pim 49.233.183.155 port 35330 [preauth]                                                                   
Jan  9 13:19:08  sshd[11465]: Connection closed by 46.101.89.150 port 43813 [preauth]                                                                                  
Jan  9 13:21:48  sshd[11467]: Connection closed by 46.101.89.150 port 58681 [preauth]                                                                                  

```

But these are without the `Bye Bye`, but are not detected by the default f2b rules on my system.

**Comment by sebres** [comment]
Well this PR is about a message with `Bye Bye [preauth]` at end.
This message coming in your excerpt together with 2 others which would cause a match.
So there are 4 different connections, and only one (second) had an sign of authentication attempt (at least provides a user name).
```
#1st:
Jan  9 13:16:32  sshd[11452]: Connection closed by 46.101.89.150 port 57490 [preauth]
#2nd:
Jan  9 13:18:29  sshd[11463]: Invalid user pim from 49.233.183.155 port 35330
Jan  9 13:18:29  sshd[11463]: Received disconnect from 49.233.183.155 port 35330:11: Bye Bye [preauth]
Jan  9 13:18:29  sshd[11463]: Disconnected from invalid user pim 49.233.183.155 port 35330 [preauth]
#3rd:
Jan  9 13:19:08  sshd[11465]: Connection closed by 46.101.89.150 port 43813 [preauth]
#4th:
Jan  9 13:21:48  sshd[11467]: Connection closed by 46.101.89.150 port 58681 [preauth]
```
But all 4 would be recognized properly in current 0.10, if one'd use `mode = aggressive` in sshd-jail.
Here is the test with 0.10.5 (release candidate):
<details><summary>Excerpt with test outputs of fail2ban-regex:</summary>

```
# grep verbose output for IP with corresponding regex:

$ fail2ban-regex -v /tmp/gh-2362.txt 'sshd[mode=aggressive]' | grep -B 1 -P '(\d+\.){3}\d+'
|   6) [1] ^[iI](?:llegal|nvalid) user <F-USER>.*?</F-USER> from <HOST>(?: (?:port \d+|on \S+|\[preauth\])){0,3}\s*$
|      49.233.183.155  Thu Jan 09 13:18:29 2020
--
|  19) [1] ^<F-NOFAIL>Received <F-MLFFORGET>disconnect</F-MLFFORGET></F-NOFAIL> from <HOST>(?: (?:port \d+|on \S+)){0,2}:\s*11:
|      49.233.183.155  Thu Jan 09 13:18:29 2020
--
|  25) [3] ^Connection <F-MLFFORGET>closed</F-MLFFORGET> by(?: authenticating user <F-USER>\S+|.+?</F-USER>)? <HOST>(?: (?:port \d+|on \S+)){0,2}\s+\[preauth\]\s*$
|      46.101.89.150  Thu Jan 09 13:16:32 2020
|      46.101.89.150  Thu Jan 09 13:19:08 2020
|      46.101.89.150  Thu Jan 09 13:21:48 2020
--
|  32) [1] ^<F-MLFFORGET>Disconnected</F-MLFFORGET>(?: from)?(?: (?:invalid|authenticating)) user <F-USER>\S+</F-USER> <HOST>(?: (?:port \d+|on \S+)){0,2} \[preauth\]\s*$
|      49.233.183.155  Thu Jan 09 13:18:29 2020
--
|- Ignored line(s):
|  Jan  9 13:18:29  sshd[11463]: Received disconnect from 49.233.183.155 port 35330:11: Bye Bye [preauth]

# output found attempts:

$ fail2ban-regex -o row ../test-filters/gh-2362-2.txt 'sshd[mode=aggressive]'
['46.101.89.150',       1578572192.0,   {'ip4': u'46.101.89.150', 'ip6': None, 'user': None, 'dns': None, 'mlfforget': u'closed', 'mlfid': u'  sshd[11452]: '}],
['49.233.183.155',      1578572309.0,   {'dns': None, 'users': set([u'pim']), 'ip6': None, 'user': u'pim', 'ip4': u'49.233.183.155', 'mlfid': u'  sshd[11463]: '}],
['49.233.183.155',      1578572309.0,   {'ip4': u'49.233.183.155', 'ip6': None, 'user': u'pim', 'dns': None, 'mlfforget': u'Disconnected', 'mlfid': u'  sshd[11463]: '}],
['46.101.89.150',       1578572348.0,   {'ip4': u'46.101.89.150', 'ip6': None, 'user': None, 'dns': None, 'mlfforget': u'closed', 'mlfid': u'  sshd[11465]: '}],
['46.101.89.150',       1578572508.0,   {'ip4': u'46.101.89.150', 'ip6': None, 'user': None, 'dns': None, 'mlfforget': u'closed', 'mlfid': u'  sshd[11467]: '}],
```
</details>

As you can see all "attempts" are properly found.

Thus the same question remains - does someone see the message `Received disconnect from ... Bye Bye [preauth]` without any other message that would cause a failure match?

**Comment by sebres** [comment]
Fixed in f77398c49d4eeb529a1684a27dcfbf5b6aaafa66 for `ddos` and `aggressive` mode, just the second message (`Disconnected from ... [preauth]`) used to identify failure on preauth phase - this message should be always written together with `Received disconnect ...`, but the fault `Disconnected ...` (in sense of DDoS) occurs frequently.

**Comment by rnestler** [comment]
> But all 4 would be recognized properly in current 0.10, if one'd use mode = aggressive in sshd-jail.
Here is the test with 0.10.5 (release candidate):

Ah I'm using the current Buster version which seems to be 0.10.2. I guess I have to install manually then and not use the distro package?

**Comment by sebres** [comment]
Sure you can.
But we're trying also to hold configs compatible between minor versions.
Although I cannot promise you, but 0.10.5th [sshd.conf](https://github.com/fail2ban/fail2ban/blob/f77398c49d4eeb529a1684a27dcfbf5b6aaafa66/config/filter.d/sshd.conf) should be compatible to  your 0.10.2th /etc/fail2ban/filter.d/sshd.conf.
Make backup, download raw, update and try it.

**Comment by rnestler** [comment]
I replaced sshd.conf as you suggested and it seems to work and detect it now. Thanks a lot!

**Pull request closed without merging**
