### PR TITLE
Fix more typos

### PR DESCRIPTION
**Pull request by szepeviktor**
Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

`typos` is a superior tool. You can see it in this PR.
Codespell uses regular expressions, typos understands source code.

From #3630

### CODE REVIEW

**Comment by szepeviktor** [comment]
I thin you mean adding it to `.codespellrc`
I propose to use `typos`.

**Comment by sebres** [comment]
I meant it introduces failure in CI now, so to pass [Codespell](https://github.com/fail2ban/fail2ban/actions/runs/6960640646/job/18940559083?pr=3636) flow it must be ignored.

As for proposal to use topos, I don't think we need 2 spell checking flows in CI, so a better of both must be chosen. Is typos supported by GHA? Or would you like to use it locally only and just check-in it in repo?

**Comment by szepeviktor** [comment]
> Is typos supported by GHA?

Yes it is.
https://github.com/marketplace/actions/typos-action
But if you look into it, it is terrible.
I run it in GHA with a few lines: https://github.com/szepeviktor/byte-level-care/blob/e0b3ee5a8aa77126e8f80eca0c55ce5026c23432/.github/workflows/spelling.yml#L31-L50

**Review by melroy89 — APPROVED** [review]
Any update? It looks good to me. Several typos fixed in general. Why not?

You might want to rebase this old PR.

**Comment by szepeviktor** [comment]
Should I remove codespell and replace it with typos, or just fix misspellings?

**Comment by melroy89** [comment]
Thank you for the quick response!

> Should I remove codespell and replace it with typos

That is too bad not to me to decide, I have **no merge** rights 😢 . Personally I like codespell. But others may say typos is superior and find more typos. 

> , or just fix misspellings?

Keep the fix spelling mistakes of course no matter what.

And the proposed rebase with master is just to be sure that there is indeed no conflict with the changes after more than 1 year later.

**Comment by szepeviktor** [comment]
> This branch has no conflicts with the base branch

It has no conflicts

**Pull request merged**
