### PR TITLE
Introduce Cloudflare API v4

### LINKED ISSUE #1420: Cloudflare API v1 sunsetting
Cloudflare is sunsetting the version of their API that the fail2ban cloudflare action is built on. See: https://blog.cloudflare.com/sunsetting-api-v1-in-favor-of-cloudflares-current-client-api-api-v4/

Their new v4 API is much expanded with different endpoints and much different semantics. This will break the current f2b cloudflare action starting in Nov 2016.

I've built some bash scripts that use the v4 API and I am testing integrating them with f2b by calling them from the cloudflare action rather than using the built-in actions.

I was going to try to fork and fix the cloudflare action to include my v4 API code, but I am actually using an older (os packaged, v. 8.x) version of fail2ban so I wouldn't actually be able to test adequately. In addition, after looking at what f2b does to execute the code defined in action files, I wasn't sure how much of my bash code would work in that context.

So I published my ban and urban scripts as a gist here: https://gist.github.com/pjv/926ece8549cd45bac4821945f6ad253c

Perhaps someone who has the f2b chops to turn that into a proper action can make use of it to update the cloudflare action before the sunsetting of their v1 API.

Note: the v4 API let's you be much more specific about how and what and where you "ban". My scripts are more or less identical in behavior to what the v1 API action currently does.

### PR DESCRIPTION
**Pull request by szepeviktor**
In the cloudflare action everyone is suggested to use API v4.
And I don't dare to contribute any actual change.

Closes #1420

### CODE REVIEW

**Comment by sebres** [comment]
Just to link - #1420, #1546

**Comment by szepeviktor** [comment]
@sebres Coud we merge it?

**Comment by sebres** [comment]
Of course and you've although changed comments only, but...
- should it still stay commented? (I heard the old API is depreciated now)
- there are at least 2 issues which provided cloudflare v4 support. Could you take a look about a suggested solutions (to merge it with your, or to close it finally).
- me self have no experience with cloudflare at all (@yarikoptic any suggestions?)

**Comment by szepeviktor** [comment]
I use the commented code myself
https://github.com/szepeviktor/debian-server-tools/blob/master/security/fail2ban-conf/action.d/cloudflare.local#L31

You may close both issues.

I wrote comment as I am not able to add tests nor provide support.

**Comment by sebres** [comment]
Should we then rather uncomment v4 API (and comment v1)?

**Comment by szepeviktor** [comment]
If you agree...

**Comment by szepeviktor** [comment]
Thank you!

**Pull request merged**
