### PR TITLE
define journalmatch setting for pure-ftps

### PR DESCRIPTION
**Pull request by weberhofer**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Thanks! Just to make sure - it does with for you if you use systemd backend for this jail?

**Comment by weberhofer** [comment]
Yes, it's working. Currently I have hundreds of blocked IPs on one of my servers using this setting.

**Comment by yarikoptic** [comment]
OK, then either you as changelog entry or I will do that later when get home and merge

**Comment by weberhofer** [comment]
@yarikoptic please do the merge, I can't.

**Pull request merged**
