### PR TITLE
#1667: Wrong paths for apache and nginx under FreeBSD

### PR DESCRIPTION
**Pull request by chtheis**
Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

Closes gh-1667

### CODE REVIEW

**Comment by sebres** [comment]
@fail2ban/maintainers Ideas?
Whats about prev versions of FreeBSD?

**Comment by chtheis** [comment]
Am 16.01.2017 um 11:04 schrieb Serg G. Brester:
> @fail2ban/maintainers
> <https://github.com/orgs/fail2ban/teams/maintainers> Ideas?
> Whats about prev versions of FreeBSD?

Pathes for apache were always wrong. I guess users configured their own 
pathes.

Pathes for nginx changed with an nginx update some time ago, this patch 
corrects for this.

All this is independent of the FreeBSD version. But, of course, valid 
for the current versions of apache and nginx.


Best regards

Christoph

**Comment by sebres** [comment]
Can you rebase this commit over 0.9 branch (master)? As long as 0.9 will be supported, master is a target branch for all forwards-compatible changes. After rebase you can switch branch in this PR (button Edit in head).
If not let me know, I'll make it for you

And please add a changelog entry...

**Comment by chtheis** [comment]
Am 17.01.2017 um 09:46 schrieb Serg G. Brester:
> Can you rebase this commit over 0.9 branch (master)? As long as 0.9 will
> be supported, master is a target branch for all forwards-compatible
> changes. After rebase you can switch branch in this PR (button Edit in head).

I've hoped 0.10 will come out soon and then I'll switch the FreeBSD port 
to 0.10. But 0.9 is OK, too.

> If not let me know, I'll make it for you

I hope I did it right this time.

> And please add a changelog entry...

That I don't understand. Do you mean the commit log? Or something in the 
file?


Christoph

**Comment by sebres** [comment]
I meant an entry in [changelog](https://github.com/fail2ban/fail2ban/blob/master/ChangeLog#L71) file

**Comment by chtheis** [comment]
Am 17.01.2017 um 12:30 schrieb Serg G. Brester:
> I meant an entry in changelog
> <https://github.com/fail2ban/fail2ban/blob/master/ChangeLog#L71> file

Ah, I thought you'll do the changes there.

OK, I tried my best ;)
But I'm not sure if that was good enough and the pull request ended up 
in fail2ban/fail2ban.


Christoph

**Comment by sebres** [comment]
further in #1673

**Pull request closed without merging**
