### PR TITLE
0.10: readme.md - added IPv6 launch logo for 0.10th branch

### PR DESCRIPTION
**Pull request by sebres**
Closes gh-1647

### CODE REVIEW

**Comment by sebres** [comment]
[Click to see how it looks](https://github.com/fail2ban/fail2ban/blob/ipv6-logo-gh-1647/README.md)

**Comment by szepeviktor** [comment]
Very nice!

**Comment by szepeviktor** [comment]
We could even add World_IPv6_launch_logo.svg to *this* repo.

**Comment by sebres** [comment]
> We could even add World_IPv6_launch_logo.svg to this repo.

I don't know, it would be a good idea - although it is 4 KB only, but it belong later to the each copy, release, etc.
BTW. I think github will replace it in the markdown html-representation with something like "...githubusercontent.com/hash/...", so it is IMHO irrelevant.

**Comment by sebres** [comment]
@yarikoptic Merge?

**Comment by szepeviktor** [comment]
Aren't `/files` deleted when making a deb/rpm etc package?

**Comment by sebres** [comment]
Maybe, but... let us do that, if something goes wrong with current http-reference...

**Pull request merged**
