### PR TITLE
Update Kerio Connect filter

### PR DESCRIPTION
**Pull request by herrbischoff**
Fixed regex for some log entries that did not get recognized and some additional error formats are added.

### CODE REVIEW

**Comment by sebres** [comment]
The test cases are must (and you'll see, travis will fail).
So for each new failregex, you should add at least one log entry into https://github.com/fail2ban/fail2ban/blob/master/fail2ban/tests/files/logs/kerio that will match each expression.

**Comment by herrbischoff** [comment]
Thanks for pointing that out. I'll get on that today as soon as I find the time.

**Comment by sebres** [comment]
Still interrested to complete? Or should I close this PR (I've no kerio to test resp. you've not provided any log-excerpt)

**Comment by herrbischoff** [comment]
Please excuse the long silence. I'll try to get to this in the coming days.

**Comment by herrbischoff** [comment]
@sebres: I have added the missing test, all checks pass now. Please review.

**Comment by sebres** [comment]
I've seen it. 
Looks good, I'll merge it in 24h if no objections follow

**Pull request merged**
