### PR TITLE
FreeIPA renames named to named-pkcs11

### PR DESCRIPTION
**Pull request by brianjmurrell**
FreeIPA renames the BIND9 named daemon to named-pkcs11, so extend the
REGEX match to look for either variant.

Signed-off-by: Brian J. Murrell <brian@interlinx.bc.ca>

### CODE REVIEW

**Comment by brianjmurrell** [comment]
Anyone to review this?

**Comment by brianjmurrell** [comment]
This (very simple) PR has been waiting over 2 years for review (and landing if acceptable).  Is there anything specific that is holding it up?

**Comment by sebres** [comment]
> Is there anything specific that is holding it up?

Nothing specific, just I wanted to rebase it to 0.10/0.11 + add some test cases covering new name.
But OK, since it is pretty simple indeed, I'll merge it now to master (with a small amend of me).
Thx!

**Comment by brianjmurrell** [comment]
Awesome and thanks!

**Pull request merged**
