### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
I have no idea what the right branch is. I'm sorry. I can adjust to another branch if requested.

- [x] **KEEP PR small** so it could be easily reviewed.

Note: this series has been sitting on my computer for a while, there are probably new spelling errors that have crept in since.

### CODE REVIEW

**Comment by sebres** [comment]
Unfortunately too many open branches resp. PR's currently, that can be affected if this will be merged (conflicts, etc). So currently blocked, but I'll try take a look soon...

**Comment by jsoref** [comment]
If you have a list of PRs that you don't want conflicts against, I should be able to merge all of them together and try to merge this PR against that amalgam, splitting out any commits that conflict.

(Basically, that's an algorithm for splitting this PR into a series of shrinking PRs.)

This repo has very few code typos, so there aren't many other ways that I could see to split the PR.

**Comment by jsoref** [comment]
(Otherwise, I'm fine w/ waiting, there's no urgency in this.)

**Comment by yarikoptic** [comment]
that sucks that we did not manage to finalize this PR to merge in all these years. FWIW
- https://github.com/fail2ban/fail2ban/pull/3630
would be the newest attempt at the same battle ;)   And there I use our `datalad run` so I could have "rerunnable" commits happen I need to rebase the branch where actions (such as `sed`'ing the typo fixes) would need to be rerun.

But as such, with 6 years age of this PR which never got updated/merged, I would just close it.

**Comment by jsoref** [comment]
I'm happy to update this PR if someone's interested in taking it.

**Pull request closed without merging**
