### PR TITLE
Update apache-badbots.conf

### PR DESCRIPTION
**Pull request by EdwardBeckett**
Useragent strings including `+http` need to be escaped to be valid.

### CODE REVIEW

**Comment by yarikoptic** [comment]
thanks!  can you adjust files/gen_badbots add well a nd add  changelog entry

**Comment by EdwardBeckett** [comment]
@yarikoptic Sure thing. Will do.

**Comment by yarikoptic** [comment]
thanx, merged and will need to not forget to adjust changelog to become a bit more descriptive ( escape +  in the regex)

**Comment by EdwardBeckett** [comment]
@yarikoptic will do chief ~ didn't want to be too presumptive or chatty ;-) next time eh?

**Comment by yarikoptic** [comment]
sure.  no problem.  thanks for the contribution!

**Comment by yarikoptic** [comment]
oh, I  have missed that you placed changelog entry to previous release entry...  could you please move it  to the to p fresh one  and  makeit more descriptive -  hard to do on the phone for me atm

**Comment by EdwardBeckett** [comment]
Sure...

**Pull request merged**
