### PR TITLE
Update pf.conf fixing #1863

### LINKED ISSUE #1863: pfctl -f
Fail2ban 0.10.x revamps the behaviour of the `pf` firewall (in `action.d/pf.conf`). While it's a commendable effort to improve the flexibility of the pf support, the current implementation has a fatal flaw: it makes extensive use of the command `pfctl -f`. This has the unfortunate effect of:

* wiping out all previously-existing firewall rules (leaving the unsuspecting user wide-open and vulnerable).
* even stomping on the firewall rules created by fail2ban itself: if `jail.d/a.local` and `jail.b/b.local` both invoke the `pf` action, the invocation of the second will wipe out the firewall rules created by the invocation of the first.

The only solution (as best as I can see) is to replace "`pfctl ...`" by "`pfctl -a f2b/<name> ...` everywhere in `action.d/pf.conf` (and then, in the main pf ruleset have an

```
anchor f2b {
  name1
  name2
  ...
}
```

This will load the dynamically-created rules produced by fail2ban, while preventing them from stomping on each other or on pre-existing rulesets.

### PR DESCRIPTION
**Pull request by koeppea**
Fix #1863
Introduce own PF anchors for fail2ban rules.

### CODE REVIEW

**Comment by sebres** [comment]
Thanks!
But test cases will have surely failed, I've made a small changes + fixed the test-cases, will push it soon.

**Comment by sebres** [comment]
Is in it. @koeppea can you please take a look over...

**Comment by koeppea** [comment]
This looks pretty good. But I'm not sure for the nested variable (`<>`). 
Because in `<pfctl>` `<name>` is implicitely included and should be expanded.
But I need to test on a FreeBSD machine. I try to manage doing this by end of this week.
Maybe @distler can afford some time to test?

**Comment by sebres** [comment]
> Because in <pfctl> <name> is implicitely included and should be expanded.

This is test-covered (exactly the test-cases that was broken on your commit), thus surely interpolated correctly. Therefore this commit does not change anything on the resulting filter-logic compared to your commit (I mean this is exactly the same output on command calls).

**Comment by sebres** [comment]
Bellow is an excerpt of the output of `fail2ban-testcases -fn -l 10 testCheckStockCommandActions` (concerning `pf`, default, multiport and allports):
<details><summary>Click to show the details</summary>

```
  DEBUG # ==================================================
  DEBUG # == j-w-pf - pf                                  ==
  DEBUG # ==================================================
  DEBUG ===== # === start === =====
  DEBUG exec-cmd: `echo "table <f2b-j-w-pf> persist counters" | pfctl -f-`
  DEBUG exec-cmd: `echo "block proto tcp from <f2b-j-w-pf> to any port <port>" | pfctl -f-`
  DEBUG ===== # === ban-ipv4 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T add 192.0.2.1`
  DEBUG ===== # === unban ipv4 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T delete 192.0.2.1`
  DEBUG ===== # === ban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T add 2001:db8::`
  DEBUG ===== # === unban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T delete 2001:db8::`
  DEBUG ===== # === stop === =====
  DEBUG exec-cmd: `pfctl -sr 2>/dev/null | grep -v f2b-j-w-pf | pfctl -f-`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T flush`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf -T kill`
  DEBUG # ==================================================
  DEBUG # == j-w-pf-mp - pf                               ==
  DEBUG # ==================================================
  DEBUG ===== # === start === =====
  DEBUG exec-cmd: `echo "table <f2b-j-w-pf-mp> persist counters" | pfctl -f-`
  DEBUG exec-cmd: `echo "block proto tcp from <f2b-j-w-pf-mp> to any port http" | pfctl -f-`
  DEBUG ===== # === ban-ipv4 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-mp`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T add 192.0.2.1`
  DEBUG ===== # === unban ipv4 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-mp`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T delete 192.0.2.1`
  DEBUG ===== # === ban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-mp`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T add 2001:db8::`
  DEBUG ===== # === unban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-mp`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T delete 2001:db8::`
  DEBUG ===== # === stop === =====
  DEBUG exec-cmd: `pfctl -sr 2>/dev/null | grep -v f2b-j-w-pf-mp | pfctl -f-`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T flush`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-mp -T kill`
  DEBUG # ==================================================
  DEBUG # == j-w-pf-ap - pf                               ==
  DEBUG # ==================================================
  DEBUG ===== # === start === =====
  DEBUG ===== # === ban-ipv4 === =====
  DEBUG exec-cmd: `echo "table <f2b-j-w-pf-ap> persist counters" | pfctl -f-`
  DEBUG exec-cmd: `echo "block proto tcp from <f2b-j-w-pf-ap> to any" | pfctl -f-`
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-ap`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T add 192.0.2.1`
  DEBUG ===== # === unban ipv4 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-ap`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T delete 192.0.2.1`
  DEBUG ===== # === ban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-ap`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T add 2001:db8::`
  DEBUG ===== # === unban ipv6 === =====
  DEBUG exec-cmd: `pfctl -sr | grep -q f2b-j-w-pf-ap`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T delete 2001:db8::`
  DEBUG ===== # === stop === =====
  DEBUG exec-cmd: `pfctl -sr 2>/dev/null | grep -v f2b-j-w-pf-ap | pfctl -f-`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T flush`
  DEBUG exec-cmd: `pfctl -t f2b-j-w-pf-ap -T kill`
```
</details>

**Comment by koeppea** [comment]
Inspecting the test output, I don't see the `-a f2b/something` parameter.
Also just for beauty, can we replace the test IPv6 address `2001:db8::` with `2001:db8::1`?

**Comment by sebres** [comment]
> Inspecting the test output, I don't see the -a f2b/something parameter.

I was also very smart :) wrong branch ... Thus the output updated now (refresh and see above).

> Also just for beauty, can we replace the test IPv6 address 2001:db8:: with 2001:db8::1?

Of course ... some time later. :)

**Comment by distler** [comment]
>Maybe @distler can afford some time to test?

I'm on MacOSX, not FreeBSD.

**Comment by sebres** [comment]
Merged in 0.10 and 0.11. 
Thank to all!

**Comment by koeppea** [comment]
Just to double confirm: Tested on FreeBSD. Is working as expected.

**Pull request merged**
