### PR TITLE
Add 'any' badips.py bancategory

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR adds the `any` badips bancategory, which can be useful, for example to add all IPs of a desired score, in a global firewall lookup table.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Just added changelog entry.

**Comment by benrubson** [comment]
I just resolved conflits.
Of course you can squash-merge if you want to have a clean commit log 👍 
Thx !

**Comment by sebres** [comment]
I assume it is still not completely correct so.
The wrong case you still have with this PR is - it will fail by ban:

Just try:
```bash
$ curl -s http://www.badips.com/add/any/192.0.2.1
{"err":"invalid category selected: any","suc":""}
```
So you can get list for `any`, but it will immediatelly fail by ban (cannot be used for ban purposes).
Thus I cannot accept the PR as it is.

**Comment by benrubson** [comment]
You can't add to `any` category.
However you can retry `any` bancategory.
This is why this PR adds `any` only to the `bancategory` option.
However `any` will not be accepted as a `category` option.
So this is OK :)

**Comment by benrubson** [comment]
You can then use for example `category=ssh`, `bancategory=any`.

**Comment by sebres** [comment]
Yeah, right.

**Comment by benrubson** [comment]
Thx 👍

**Pull request merged**
