### PR TITLE
dovecot filter enhancement to catch sql password mismatch errors

### PR DESCRIPTION
**Pull request by BoresXP**
…mismatch errors;

Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
- [x] **CONSIDER adding a unit test** if your PR resolves an issue
- [x] **LIST ISSUES** this PR resolves
- [x] **MAKE SURE** this PR doesn't break existing tests
- [x] **KEEP PR small** so it could be easily reviewed.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code
- [x] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by sebres** [comment]
I would like to see an example log-entry resp. new test in https://github.com/fail2ban/fail2ban/blob/0.11/fail2ban/tests/files/logs/dovecot covering this failure.

BTW please rebase it relative 0.10 if you can.

**Comment by BoresXP** [comment]
@sebres 
> I would like to see an example log-entry resp. new test in https://github.com/fail2ban/fail2ban/blob/0.11/fail2ban/tests/files/logs/dovecot covering this failure.

Done

**Comment by BoresXP** [comment]
@sebres 
> BTW please rebase it relative 0.10 if you can.

Does it mean opening new pull request? Because this one is based on 0.11.
Or can you point me on a guide for it please.

**Comment by sebres** [comment]
I've rebased it for you (first into 0.10 and merged in your 0.11)... waiting for test-cases.
Will merge if OK,
Thanks!

**Pull request merged**
