### PR TITLE
Add unban script for iptables

### PR DESCRIPTION
**Pull request by kyle95wm**

### CODE REVIEW

**Comment by kyle95wm** [comment]
Does this mean you're not merging my pr?

**Comment by kyle95wm** [comment]
I don't understand the whole "checks" thing. All I want is to make it easier for people to un-ban people from IPTABLES

**Comment by yarikoptic** [comment]
but we  have already fail2ban-client unban,  so why  this iptables  specific one?

**Comment by kyle95wm** [comment]
are you sure? I've tried every possible way but my script does what I want. Whats the syntax exactly?

**Comment by kyle95wm** [comment]
Okay nevermind I just used the build from the repo here and I saw there was an unban option looks like the debian package is outdated by a lot. Just one question before we close this, is there a way to uninstall if for whatever reason we need to?

**Comment by sebres** [comment]
possible a "duplicate" issue of #980

**Comment by yarikoptic** [comment]
@sebres -- I don't really see how this one (unban action) relates to 980.
@kyle95wm backports for debians of fail2ban are available from the neurodebian (unannounced -devel carries 0.9. series as well) see e.g http://sourceforge.net/p/fail2ban/mailman/message/32143078/

uninstall -- would depend on how you installed it so can't give you exhaustive answer... but if you just "setup.py install"ed it -- you would need to manually remove   /usr/local/*bin/*fail2ban* and wherever it installed the module under /usr/local/lib somewhere -- just search for fail2ban

**Comment by sebres** [comment]
@yarikoptic I thought that stop of f2b-service resp. unban an IP, had left any leaks in iptables...

**Pull request closed without merging**
