### PR TITLE
Simplistic Docker config for deploying the server in a container

### PR DESCRIPTION
**Pull request by MarcPartensky**
Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [x] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by sebres** [comment]
Just to reference with https://github.com/crazy-max/docker-fail2ban
Not against the PR, just... I'm not really familiar with an operation of fail2ban inside docker container, but I guess this "simplistic" approach could have several issues (probably solved in @crazy-max's docker-fail2ban repo), wouldn't it?
@crazy-max Any thoughts?

**Comment by crazy-max** [comment]
> but I guess this "simplistic" approach could have several issues

Yes indeed, the Dockerfile from this PR will not work as some additional packages are required: https://github.com/crazy-max/docker-fail2ban/blob/master/Dockerfile. Maybe we could move `crazy-max/docker-fail2ban` to `fail2ban/docker`? It would bring more of visibility and make it easier to maintain/collab and move issues for triage around the org.

**Comment by sebres** [comment]
> Maybe we could move crazy-max/docker-fail2ban to fail2ban/docker?

Agree. See https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository and ping me if some steps must be handled from us (e. g. accepting transfer and becoming the necessary rights hereafter).

**Comment by MarcPartensky** [comment]
> > but I guess this "simplistic" approach could have several issues
> 
> Yes indeed, the Dockerfile from this PR will not work as some additional packages are required: https://github.com/crazy-max/docker-fail2ban/blob/master/Dockerfile. Maybe we could move `crazy-max/docker-fail2ban` to `fail2ban/docker`? It would bring more of visibility and make it easier to maintain/collab and move issues for triage around the org.

Yes I wasn't aware of this repository. It is what I needed. Changing the name to bring more visibility would be great! Thanks for reviewing awesome job!

**Pull request closed without merging**
