### PR TITLE
Using native firewalld ipset implementation

### LINKED ISSUE #2614: Action firewallcmd-ipset using native firewalld ipset implementation
@grooverdan @sebres Created this issue just for curious to know why actions in [firewallcmd-ipset.conf](https://github.com/fail2ban/fail2ban/blob/master/config/action.d/firewallcmd-ipset.conf) fail2ban config do not use native firewalld ipset implementation? As described here for example.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-setting_and_controlling_ip_sets_using_firewalld

Also with warning in the end: 

> Red Hat does not recommend using IP sets that are not managed through firewalld

### PR DESCRIPTION
**Pull request by mspolitaev**
By creating additional action file firewallcmd-ipset-native.conf

Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [ ] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

Closes #2614, #1290

### CODE REVIEW

**Comment by sebres** [comment]
Thanks!
Merged now, but I'll still try to combine both ipset actions using some parameter like `ipset-type` (set to `native` per default).

**Comment by sebres** [comment]
Hmm... Now I have several questions with this action (after an attempt to combine both actions):
- it uses permanent ipset - persistence issue was touched in #1474 inter alia and I'm unsure it must be targeted here (be part of this PR);
- firewall-cmd seems not to have any sub-command to flush its native created ipset, so it is impossible to implement `actionflush`;
- the action does not support IPv6 (set would miss `--option=family=inet6` by its creation);
- the control of timeout in ipset is not so good (we had several issues already, e. g. #2670, thus now it is under fail2ban control solely)

I'm still trying to "fix" all that in combined action, but the issue with missing flush functionality makes it hardly possible at the moment.

**Comment by sebres** [comment]
Done in c7a86b4616ef1bd43cf96874710b53b42d065684:
- combines actions `firewallcmd-ipset` and `firewallcmd-ipset-native` (parameter `ipsettype=firewalld`), for example:
`banaction = firewallcmd-ipset[ipsettype=firewalld]`
- IPv6-capability for firewalld ipset;
- no internal timeout handling by default;
- no permanent rules yet;

The issue with `actionflush` is still there, therefore I wouldn't recommend to use this in production (let alone I don't think usage of firewalld actions provides any benefit compared with actions using native net-filters like `iptables/ipset` or `nftables`).

**Comment by mspolitaev** [comment]
@sebres glad to help, i am out of context of the problem unfortunately. Hope it's not broke anything, only improve)

**Comment by sebres** [comment]
**Important:** for people landing here to use `firewalld` ipset implementation:
In `action.d/firewallcmd-ipset.conf` old parameter `ipsettype` initially added here for an ipset-backend, renamed since 17daf0ec7887a3c436093b56c8720645ef4ccf62 to `ipsetbackend`, because it is really backend and not a type and because new parameter `ipsettype` will be used for the real set type (see #3760).
So for example one would use this now:
```ini
banaction = firewallcmd-ipset[ipsetbackend=firewalld]
```

*I know it is not quite compatible change, but... (only if someone already used `ipsettype` previously)... 
Anyway, otherwise it'd be really confusing, so a rename was better choice in my opinion.*

**Pull request merged**
