### PR TITLE
ENH: log also threadName -- helps a lot while debugging multiple jails

### PR DESCRIPTION
**Pull request by yarikoptic**
but may be it should be in effect only in DEBUG mode?

### CODE REVIEW

**Comment by leeclemens** [comment]
Sorry if I'm just missing something, but why is "debug mode which is pretty much unsupported for recidive" not supported by a specific jail? I admit I haven't checked this out in the source...but it just seems too strange to be true.

**Comment by yarikoptic** [comment]
On Tue, 07 Jul 2015, Lee Clemens wrote:

>    Sorry if I'm just missing something, but why is "debug mode which is
>    pretty much unsupported for recidive" not supported by a specific jail? I
>    admit I haven't checked this out in the source...but it just seems too
>    strange to be true.

recidive is based on parsing the fail2ban.log file... if we increase
loglevel to debug -- it would cause "snake eating its own tail"
situation while recidive jail reading new lines from the log file and
reporting back on that into the same file...

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by leeclemens** [comment]
fundamentally flawed, as I've already mentioned.

**Comment by yarikoptic** [comment]
yeah -- let's dump for now ;) Cheers

**Pull request closed without merging**
