### PR TITLE
Fixed issue 1548

### PR DESCRIPTION
**Pull request by sergey-safarov**
Removed regex binding to start of log string.
Added support of log failued to IPv6 addresses and to domain names

### CODE REVIEW

**Comment by sergey-safarov** [comment]
Link to issue https://github.com/fail2ban/fail2ban/issues/1548

**Comment by sebres** [comment]
If I correct understood, the prefix by systemd-filter looks like like `Sep 18 04:42:43 fs2.company.org freeswitch[1336]: `...
Then I don't understand, why the removing of anchor should help to resolve this issue - because it still expected `\.\d+`, so it cannot be found in provided prefix...
BTW. Removing of anchor is not a solution, rather a workaround.

Can you provide the full log-line resp. excerpt from your journal of freeswitch, that this PR concerns?

**Comment by sergey-safarov** [comment]
As example
Sep 25 18:57:58 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 18:57:58.150982 [WARNING] sofia_reg.c:2889 Can't find user [201@217.12.247.210] from 23.239.87.51
Sep 25 18:57:58 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 18:57:58.150982 [WARNING] sofia_reg.c:1720 SIP auth failure (INVITE) on sofia profile 'sipinterface_1' for [9810972597751739@217.12.247.210] from ip 23.239.87.51

Expression "\.\d+" in provided example will match ".150982".

**Comment by sebres** [comment]
Really, get date twice?
We could have additionally something wrong within systemd backend (or freeswitch writes indeed the datetime in message)...

Can you please provide the output of `journalctl -o verbose ...` for one entry?

**Comment by sebres** [comment]
Did you really use `backend = systemd`? Because our systemd-filter produces the date-time (the first date in your examples) in iso-format, so it looks like `2016-09-26T13:16:32.981746`...
What you've used to generate the latest examples?

**Comment by sergey-safarov** [comment]
@sebres For first questions
Yes, date used twice. First date is generated by systemd. This timeshtamp when message is logged.
Second date if logged by FreeSwitch. For FreeSwitch is importand to know timestamps with miliseconds. This timeshtamp is call processing timeshtamp.

Example of one systemd message is follows

-- Logs begin at Sun 2016-09-25 20:54:12 GMT, end at Mon 2016-09-26 13:32:40 GMT. --
Sun 2016-09-25 20:54:12.963019 GMT [s=d016450f070a4a20b729938b5ea67223;i=4798e;b=ead0163642de4f8c86d09c56991d148d;m=fb2e65fc84;t=53d5b36b900dc;x=ad7c4
    _TRANSPORT=syslog
    PRIORITY=4
    SYSLOG_FACILITY=17
    SYSLOG_IDENTIFIER=freeswitch
    SYSLOG_PID=122921
    MESSAGE=2016-09-25 20:54:12.951003 [WARNING] mod_kazoo.c:751 Erlang node connection failed - ensure your cookie matches 'tDLn29rRGxaAmTCL48L4wVxhf
    _PID=122921
    _UID=998
    _GID=2
    _COMM=freeswitch
    _EXE=/usr/bin/freeswitch
    _CMDLINE=/usr/bin/freeswitch -ncwait
    _CAP_EFFECTIVE=0
    _SYSTEMD_CGROUP=/system.slice/freeswitch.service
    _SYSTEMD_UNIT=freeswitch.service
    _SYSTEMD_SLICE=system.slice
    _SELINUX_CONTEXT=system_u:system_r:unconfined_service_t:s0
    _SOURCE_REALTIME_TIMESTAMP=1474836852963019
    _BOOT_ID=ead0163642de4f8c86d09c56991d148d
    _MACHINE_ID=fb0d7fa728f54f4bb04a0c317b79ae6d
    _HOSTNAME=fs1.voip.rcsnet.ru

**Comment by sergey-safarov** [comment]
@sebres responce for second question

[root@fs1 fail2ban]# fail2ban-server -V
Fail2Ban v0.9.1

Copyright (c) 2004-2008 Cyril Jaquier, 2008- Fail2Ban Contributors
Copyright of modifications held by their respective authors.
Licensed under the GNU General Public License v2 (GPL).

Written by Cyril Jaquier <cyril.jaquier@fail2ban.org>.
Many contributions by Yaroslav O. Halchenko <debian@onerussian.com>.

[root@fs1 fail2ban]# cat jail.conf | grep backend
# "backend" specifies the backend used to get files modification.
#              Specifying "logpath" is not valid for this backend.
# auto:      will try to use the following backends, in order:
backend = auto

[root@fs1 fail2ban]# journalctl -b1 | grep -P "Can't find user|SIP auth failure" | head -n 5
Sep 25 20:55:21 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 20:55:21.990982 [WARNING] sofia_reg.c:2889 Can't find user [20@217.12.247.210] from 23.239.87.51
Sep 25 20:55:21 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 20:55:21.990982 [WARNING] sofia_reg.c:1720 SIP auth failure (INVITE) on sofia profile 'sipinterface_1' for [810972597751739@217.12.247.210] from ip 23.239.87.51
Sep 25 20:55:23 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 20:55:23.931013 [WARNING] sofia_reg.c:2889 Can't find user [20@217.12.247.210] from 23.239.87.51
Sep 25 20:55:23 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 20:55:23.931013 [WARNING] sofia_reg.c:1720 SIP auth failure (INVITE) on sofia profile 'sipinterface_1' for [9810972597751739@217.12.247.210] from ip 23.239.87.51
Sep 25 21:09:58 fs1.voip.rcsnet.ru freeswitch[122921]: 2016-09-25 21:09:58.730984 [WARNING] sofia_reg.c:2889 Can't find user [111@217.12.247.210] from 23.239.87.51

**Pull request closed without merging**
