### PR TITLE
Added configuration for opensuse paths

### PR DESCRIPTION
**Pull request by weberhofer**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Great, thanks -- while at it, could you add a ChangeLog entry and yourself to THANKS? ;-)  and I would like to wait for some feedback from other @fail2ban/contributors who might have some opensuse experience to verify/comment on. if noone chimes in, I will merge it in 2 days

**Comment by weberhofer** [comment]
The path definition is in use for a while in the public development project of openSUSE at https://build.opensuse.org/package/show/security/fail2ban where I'm the maintainer; I have slightly modified it for usage in the 0.9.3 version.

**Comment by szepeviktor** [comment]
Maybe none of the contributors have Opensuse.

**Comment by yarikoptic** [comment]
may be may be... merged now  ;-)

**Pull request merged**
