### PR TITLE
Update asterisk.conf

### PR DESCRIPTION
**Pull request by 3eBoP**
Changed regex for "Call from ...". Sometimes extension can have a plus symbol (+) because they can be phone number.

### CODE REVIEW

**Comment by yarikoptic** [comment]
we would need an example failing line added to fail2ban/tests/files/logs/asterisk, and ideally an entry to ChangeLog ;)

**Comment by 3eBoP** [comment]
What kind of exemple ?

**Comment by yarikoptic** [comment]
just look into that file and provide example with the phone #, i.e. the case your adjusted regexp is catching now

**Comment by 3eBoP** [comment]
Ok, here is several examples I had on my own server : 
[2016-01-28 10:22:27] NOTICE[3477][C-000003bb] chan_sip.c: Call from '' (xxx.xxx.xxx.xxx:xxxx) to extension '++441772285411' rejected because extension not found in context 'default'.
[2016-01-28 10:23:57] NOTICE[3477][C-000003bc] chan_sip.c: Call from '' (xxx.xxx.xxx.xxx:xxxx) to extension '+441772285403' rejected because extension not found in context 'default'.
[2016-01-28 10:34:31] NOTICE[3477][C-000003c3] chan_sip.c: Call from '' (xxx.xxx.xxx.xxx:xxxx) to extension '0+441772285407' rejected because extension not found in context 'default'.

**Comment by 3eBoP** [comment]
Is that ok ?

**Comment by yarikoptic** [comment]
good examples... add to that file (with some IPish IP like others

On Thu, 28 Jan 2016, 3eBoP wrote:

>    Ok, here is several examples I had on my own server :
>    [2016-01-28 10:22:27] NOTICE[3477][C-000003bb] chan_sip.c: Call from ''
>    (xxx.xxx.xxx.xxx:xxxx) to extension '++441772285411' rejected because
>    extension not found in context 'default'.
>    [2016-01-28 10:23:57] NOTICE[3477][C-000003bc] chan_sip.c: Call from ''
>    (xxx.xxx.xxx.xxx:xxxx) to extension '+441772285403' rejected because
>    extension not found in context 'default'.
>    [2016-01-28 10:34:31] NOTICE[3477][C-000003c3] chan_sip.c: Call from ''
>    (xxx.xxx.xxx.xxx:xxxx) to extension '0+441772285407' rejected because
>    extension not found in context 'default'.

>    -
>    Reply to this email directly or view it on GitHub.

>    Link:
>    https://github.com/fail2ban/fail2ban/pull/1309#issuecomment-176195156

-- 
Yaroslav O. Halchenko
Center for Open Neuroscience     http://centerforopenneuroscience.org
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Comment by 3eBoP** [comment]
I don't get you ... you want me to add these exemples to ChangeLog file (I'm french, sorry for not understanding :) ?

**Comment by yarikoptic** [comment]
nope -- to fail2ban/tests/files/logs/asterisk

**Comment by 3eBoP** [comment]
Ok, just done it.

**Comment by yarikoptic** [comment]
you should have pushed to the same branch (patch-1) to have this PR updated... I guess you are just trying to do it all via github web interface which doesn't let you... if you can't push to that patch-1 "manually", let me know I will do all the juggling myself

**Comment by 3eBoP** [comment]
You guess right. Please do that magic trick for me :)

**Comment by 3eBoP** [comment]
Have you managed to merge all my files ?

**Comment by sebres** [comment]
Further in #1319 (squashed commits and little bit rewritten from me)

**Pull request closed without merging**
