### PR TITLE
fix sshd rule

### PR DESCRIPTION
**Pull request by MatthieuBarbu**
just remove the space before ":11" line 52 because don't match on my Debian 9 stretch with version 0.10.3 of fail2ban
I don't know if this is wrong on all OS

### CODE REVIEW

**Comment by sebres** [comment]
Thank you!
I've rebased it to 0.10 and fixed backward-compatibility the same way (with optional space) similar to other cases (`\s*3:`, `\s*14:`).
I'll merge it if the tests have been passed.

**Comment by benrubson** [comment]
Perhaps we could think about backporting this to Debian package v0.9.6 so that this issue would be corrected in the next update of the stable Debian package ?
@yarikoptic ?
Many thx 👍

**Comment by sebres** [comment]
Perhaps better would be upgrade the package in debian stretch to 0.10th too? :)
Version 0.9 is really buggy and (whisper) even a bit vulnerable in one or other point...

**Comment by benrubson** [comment]
That would be a good thing yes 👍 
But will Debian stable branch allow a jump from 0.9.6 to 0.10 ? :-/

**Pull request merged**
