### PR TITLE
Merge Apache SNI error / misredirect attempts rules

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR follows #2097, it merges Apache SNI related filter rules.

Thank you 👍 

Ben

### CODE REVIEW

**Comment by benrubson** [comment]
Hi @sebres,
Did you have time to look at this ?
Many thanks 👍

**Comment by sebres** [comment]
I don't know it's good to combine two almost different messages...
If your intention is to shorten a count of regexp's (e. g. speed-up the search a bit), one could indeed do that (just less clearly hereafter)..

In this case following will be a bit better (it has one of branches less):
```diff
-^(?:No )?[Hh]ostname \S+ provided via SNI(?:, but no hostname provided| and hostname \S+ provided| for a name based virtual host)\b
+^(?:No h|H)ostname \S+ provided via SNI(?:, but no hostname provided| and hostname \S+ provided| for a name based virtual host)\b
```

**Comment by benrubson** [comment]
Thank you for your answer @sebres 👍 
Yes main goal was to reduce number of regular expressions.
As they are both related to SNI, to the same part of Apache's code, to the same PR (#2097), I though it could be worth it.
_(I've pushed your improvement if you decide to merge this)_

**Comment by benrubson** [comment]
Thx Sergey 👍

**Pull request merged**
