### PR TITLE
BF: 'create' /var/run/fail2ban on systems with /var/run

### PR DESCRIPTION
**Pull request by yarikoptic**
Should overcome problems of some users installing using setup.py install

### CODE REVIEW

**Comment by yarikoptic** [comment]
if noone sees obvious problems @fail2ban/contributors  ?  I have filed #1089 regarding what caused travis to "Fail"

**Comment by leeclemens** [comment]
Do you have a link to an issue or email where someone experienced and issue this aims to resolve? I don't necessarily see any harm in it, just not sure what problem this specific PR aims to solve.

**Comment by yarikoptic** [comment]
issue would be experienced by anyone who is trying to just install fail2ban with "python setup.py install" I guess, and somewhat relates to #168 which you have just closed ;-)

**Comment by leeclemens** [comment]
#168 is not closed - I did comment on it though, suggesting it may be closable :)

I guess I'm not sure how this PR addresses the issue...does this change create the directory "/var/run/fail2ban" if it does not already exist? i.e. does having a path in data_files automatically create the directory (I lack experience in setuptools stuff like this, I admit).

**Comment by leeclemens** [comment]
Well, hey, if I wasn't so lazy I might see it does create the directory as `root:root` `0755`. Didn't personally test on a system without "/var/run", but seems reasonable to me.

**Pull request merged**
