### PR TITLE
SSHd add Bad protocol version message

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR adds the `Bad protocol version identification '.........' from A.B.C.D port 1234` message to the SSHd filter, as discussed in #1284.

Thank you very much 👍

### CODE REVIEW

**Comment by benrubson** [comment]
I don't really know why the test fails...
Any hint ?
Thank you 👍

**Comment by sebres** [comment]
There is still another test filter (zzz-sshd-obsolete-multiline) which covers sshd test file (but you've extended a sshd filter only).
But you don't need to fix this - we've still another tasks for sshd, so I'll cherry-pick your commit and merge all later.

**Comment by benrubson** [comment]
OK, perfect, many thanks @sebres 👍

**Comment by benrubson** [comment]
While here, some news about this perhaps @sebres ? :)
Many thanks :)

**Comment by benrubson** [comment]
To help I had a look at `zzz-sshd-obsolete-multiline` but sounds like it references `sshd`, so I'm not really sure how to deal with it :)

**Comment by benrubson** [comment]
Should be OK with my last commit 👍

**Comment by benrubson** [comment]
Let's merge this @sebres as it's now OK ?
Thank you again 👍

**Comment by sebres** [comment]
> as it's now OK ?

Well, I don't really like your regexp, because is not anchored from right and a catch-all in the middle before the host IP, and although it does not allow a direct injection (illustrated in eb308d0fc86709dbb638618c76d10f1bd23e57f2) because it's greedy, and it is not applicable on other messages due to the anchor left, it remains a catch-all (with all cons of it).

Of course the prefilter with `prefregex` eliminates several disadvantages of that (the anchored part is fixed), so at least in new filter it's OK...

Well, the inject is covered now, let us merge it.

**Comment by benrubson** [comment]
Many thanks @sebres for your detailed explanation, and finally for your merge 👍

**Pull request merged**
