### PR TITLE
Documentation: explicit enumeration of backend and usedns options

### PR DESCRIPTION
**Pull request by pheanex**
Analogous to
["set logtarget <TARGET>", "sets logging target to <TARGET>. Can be STDOUT, STDERR, SYSLOG or a file"].

### CODE REVIEW

**Comment by yarikoptic** [comment]
although not sure if not too long

**Comment by pheanex** [comment]
It's as long as the mentioned "logtarget".
I found it quite helpful to have a short overview on possible options, maybe others too?
Consitency -> enumerate options everytime or never?
Its also the same with "usedns".

**Comment by yarikoptic** [comment]
Well, with some, like backend, available values in the end depend on available backends, e.g. pyinotify will not be a good value if no pyinotify is available. 
I agree though that explicit enumeration where not prohibitively long would be a good thing :-)

**Comment by pheanex** [comment]
They are possible options and also mentioned in jail.conf.
Mentioning and explaining those options there => enumerationg available options in help?
Nevertheless i'm just looking for the consistency. (Which would be?)

**Pull request closed without merging**
