### PR TITLE
Added systemd compatibility with Ubuntu 16.04 LTS

### PR DESCRIPTION
**Pull request by ItsAdventureTime**
[fail2ban.service.zip](https://github.com/fail2ban/fail2ban/files/236581/fail2ban.service.zip)

Before submitting your PR, please review the following checklist:

- [x] **CONSIDER adding a unit test** if your PR resolves an issue
- [x] **LIST ISSUES** this PR resolves
- [x] **MAKE SURE** this PR doesn't break existing tests 
- [x] **KEEP PR small** so it could be easily reviewed.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code
- [x] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines 
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by yarikoptic** [comment]
we are shipping configuration files as if fail2ban installed system wide not under /usr/local so I don't see us merging this PR, and in general those files should be installed by the distribution package, nothing for user to worry about. If you want recent package of fail2ban for 16.04 -- use pkg from neurodebian: http://neuro.debian.net/pkgs/fail2ban.html?highlight=fail2ban

**Comment by ItsAdventureTime** [comment]
Oh sorry. I just cloned this git, I didn't install the one from the repository in order to get the latest version.

**Comment by ItsAdventureTime** [comment]
So, how can I fix it? If I have to remove it, how can I remove it if I manually installed it?

**Comment by ItsAdventureTime** [comment]
Thanks for providing the link for this http://neuro.debian.net/install_pkg.html?p=fail2ban (How about if I am using CentOS and would like to use the latest version (unstable) of fail2ban? Do you have something similar to the neuro debian thing? I'm guessing the neuro debian thing is like PPAs for Ubuntu?

**Pull request closed without merging**
