### PR TITLE
add support for the CSF firewall

### PR DESCRIPTION
**Pull request by tjikkun**
CSF is comparable to APF, this action is based on the APF one.

### CODE REVIEW

**Comment by yarikoptic** [comment]
not familiar with this non-FOSS contraption... anyone of @fail2ban/contributors has heard/used CSF?

**Comment by szepeviktor** [comment]
http://configserver.com/cp/csf.html
Seems like it has simular functionality to Fail2ban.

**Comment by parsmizban** [comment]
Please add this action, it is very useful

**Comment by billynoah** [comment]
Is there some reason this was never pulled? I used the csf action for a server recently and it works fine.

**Pull request merged**
