### PR TITLE
Update bsd-ipfw.conf

### PR DESCRIPTION
**Pull request by ache**
Deleting not existent is not error.
Adding already present is not error.
Otherwise all those entries becomes stale forever, not removed and its number increases over time.

### CODE REVIEW

**Comment by ache** [comment]
Close #893

**Comment by yarikoptic** [comment]
Thanks @ache -- looks sane to me but I wonder if robust, e.g. wouldn't message depend on locale?
alternatively:  we don't have 'actioncheck' so not sure how, but -- is there a way to list corresponding table and then simply do not run the command if corresponding ban is already in place (or already removed)?  that imho could be cleaner

**Comment by ache** [comment]
1) Currently ipfw don't call setlocale() so always operates with "C" locale.
2) It is possible to list: 
ipfw table <num> list
but this list can be really big, causing unnecessary I/O, better relay on one line error diagnostic.

**Comment by yarikoptic** [comment]
@fail2ban/contributors anyone on FreeBSD could check this one out?

**Pull request merged**
