### PR TITLE
Create filter for Dante SOCKS server

### PR DESCRIPTION
**Pull request by al42and**
Creates filter for [Dante](https://www.inet.no/dante/index.html) server.

Limitations: I only tested it with "username" authentication mode and Dante 1.4.1 (from Debian 9), as this is the configuration I have running.

Before submitting your PR, please review the following checklist:

- [X] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against certain release version, choose `0.9`, `0.10` or `0.11` branch,
      for dev-edition use `master` branch: selected **master**
- [X] **CONSIDER adding a unit test** if your PR resolves an issue: does not resolve any issues
- [X] **LIST ISSUES** this PR resolves: does not resolve any issues
- [X] **MAKE SURE** this PR doesn't break existing tests: tests pass on my machine
- [X] **KEEP PR small** so it could be easily reviewed
- [X] **AVOID** making unnecessary stylistic changes in unrelated code
- [X] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by Loriowar** [comment]
You forgot about a follow case: "error after reading 1 byte~~s~~ in 1 second~~s~~". This may be fixed in this way: `error after reading \d+ byte(s)? in \d+ second(s)?`

**Comment by sebres** [comment]
No idea it will be logged this way, but... please don't use capturing groups here, so because each letter is a token in regex, it is enough to change:
```diff
-error after reading \d+ bytes in \d+ seconds
+error after reading \d+ bytes? in \d+ seconds?
```

**Comment by al42and** [comment]
Nice catch, thanks! It is indeed [a possible logging output](https://github.com/notpeter/dante/blob/master/dante/sockd/sockd_negotiate.c#L674).

Fixed and added a test for this particular case.

Also rebased the whole branch to avoid unrelated failed tests.

**Comment by maximmasiutin** [comment]
Would you please consider accepting this pull request?

**Comment by al42and** [comment]
@maximmasiutin, I resolved the conflicts, but I don't have dante instance readily available. Could you check if the log format used here is still relevant?

**Comment by sebres** [comment]
done

**Comment by maximmasiutin** [comment]
> @maximmasiutin, I resolved the conflicts, but I don't have dante instance readily available. Could you check if the log format used here is still relevant?

@al42and - I will check now.

**Comment by maximmasiutin** [comment]
I have installed fail2ban from source and configured it to monitor Dante. Will simulate attacks and let you know how it worked.

**Comment by maximmasiutin** [comment]
@al42and - Thank you, however, the regex was incomplete, I have addressed this issue in the pull request to update the regex to work on a real Dante server instance - please see https://github.com/fail2ban/fail2ban/pull/3410 #3410

**Comment by maximmasiutin** [comment]
> done

@sebres Thank you, however, the regex was incomplete, I have addressed this issue in the pull request to update the regex to work on a real Dante server instance - please see https://github.com/fail2ban/fail2ban/pull/3410

**Pull request merged**
