### PR TITLE
WIP: Make Abusix lookup compatible with Dash

### PR DESCRIPTION
**Pull request by jangrewe**
Before submitting your PR, please review the following checklist:

- [x] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
- [ ] **CONSIDER adding a unit test** if your PR resolves an issue
- [x] **LIST ISSUES** this PR resolves
- [ ] **MAKE SURE** this PR doesn't break existing tests
- [ ] **KEEP PR small** so it could be easily reviewed.
- [ ] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by sebres** [comment]
So you want resolve one dependency by introducing another one? I mean `tac` (it is always available by any posix-systems?).
Additionally test cases failed, so something is wrong there (maybe, usage of `${IP}` before declared?)...
Some test cases are a little bit artificial (replace something within test-case with output to stdout instead of real work), it could be just a mistake... ATM no time to check it.

**Comment by jangrewe** [comment]
The "WIP:" is supposed to mean "Work In Progress", so it's not done yet.
`tac` is part of `coreutils`, so if you're on a system that has `dig`, or Fail2ban itself, installed, i think it's safe to assume that the `coreutils` packages is already installed.
Regarding the tests: i'll have a look at those when my modifications are completed.

**Comment by jangrewe** [comment]
I had a look why the test fails (after my recent fix), and it's pretty obvious:

```
======================================================================

FAIL: testComplexMailActionMultiLog (fail2ban.tests.servertestcase.ServerConfigReaderTests)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "./fail2ban/tests/servertestcase.py", line 1725, in testComplexMailActionMultiLog

    self.assertLogged(*tests['ip4-ban'], all=True)

  File "./fail2ban/tests/utils.py", line 670, in assertLogged

    self.fail("%r was not found in the log: ===\n%s===" % (s_, logged))

AssertionError: 'mail -s Abuse from 87.142.124.10 abuse-1@abuse-test-server abuse-2@abuse-test-server' was not found in the log: ===
```

Yup, that line is not in the log indeed, as the purpose of the script is to get the abuse contact and send the mail there, not to the pre-defined test addresses ;-)

But that part works fine!
```
[...]
 -- stdout: 'Lines containing failures of 87.142.124.10 (max 2)'
 -- stdout: './fail2ban/tests/files/testcase01.log:Dec 31 11:59:59 [sshd] error: PAM: Authentication failure for kevin from 87.142.124.10'
 -- stdout: './fail2ban/tests/files/testcase01a.log:Dec 31 11:55:01 [sshd] error: PAM: Authentication failure for test from 87.142.124.10'
 -- stdout: 'mail -s Abuse from 87.142.124.10 "abuse@telekom.de"'
```

I haven't figured out where that address comes from (or the structure of the tests in general), but that should be easily fixable for somebody who knows this.

Is suspect that /bin/sh in that Vagrant box is also using Bash instead of Dash, so i'm not quite done yet...

**Comment by jangrewe** [comment]
I just noticed that my box is now sending complaint mails, which probably means that Dash only had an issue with Arrays, but subshells are working fine.
Now if anyony could have a look at the tests...

**Comment by sebres** [comment]
PR for #1684

**Comment by jangrewe** [comment]
Thanks @sebres , i've been running my patched version for the last week, and it's working fine so far.

**Comment by sebres** [comment]
I've closed this because of another solution, with better handling using new tag `<ip-rev>` in our 0.10th version, see complain.conf in #1698.

Your solution can be used in previous versions (0.9.x), where tag `<ip-rev>` is not implemented.

**Pull request closed without merging**
