### PR TITLE
New command `fail2ban-client get <JAIL> banip`

### LINKED ISSUE #1916: Feature request: fail2ban-client get <JAIL> banip
Dear developers,

How about implement `fail2ban-client get <JAIL> banip`?

I know we can get the banned ip addresses with command `fail2ban-client status <JAIL>`, but it still requires some shell commands to get a list of banned ip addresses. With `fail2ban-client get <JAIL> banip`, it will be much simpler.

### PR DESCRIPTION
**Pull request by psvi**
This PR adds new command `fail2ban-client get <JAIL> banip` to get the banned ip addresses.
Closes #1916 

Before submitting your PR, please review the following checklist:

- [ ] **CHOOSE CORRECT BRANCH**: if filing a bugfix/enhancement
      against 0.9.x series, choose `master` branch
- [x] **CONSIDER adding a unit test** if your PR resolves an issue
- [x] **LIST ISSUES** this PR resolves
- [x] **MAKE SURE** this PR doesn't break existing tests
- [x] **KEEP PR small** so it could be easily reviewed.
- [x] **AVOID** making unnecessary stylistic changes in unrelated code
- [ ] **ACCOMPANY** each new `failregex` for filter `X` with sample log lines
      within `fail2ban/tests/files/logs/X` file

### CODE REVIEW

**Comment by sebres** [comment]
I've an amend with small review and few new enhancements:
* ip-list is sorted now (by end of ban) per default;
* now it is possible to provide separator-character as extra-parameter after `get <jail> banip ?sep-char?` (default is space)
* extended with new option `--with-time` to provide more pretty and informative result (separated by new-line, including time strings: time of ban + ban-time = end of ban):
```
$ f2b get test-jail banip
192.0.2.1 192.0.2.2
$ f2b get test-jail banip ', '
192.0.2.1, 192.0.2.2
$ f2b get test-jail banip --with-time
192.0.2.1    2019-01-06 22:24:48 + 300 = 2019-01-06 22:29:48
192.0.2.2    2019-01-06 22:24:48 + 600 = 2019-01-06 22:34:48
```
Pushed here in your branch.

**Comment by psvi** [comment]
Thank you for your time @sebres

**Comment by mtompkins** [comment]
It would be useful if we could pass the ban-time value/variable as a tag to the action so that we can communicate this back in any logging we are doing external to f2b. 

In other words, currently:
```
# Option:  actionban
# Notes.:  command executed when banning an IP. Take care that the
#          command is executed with Fail2Ban user rights.
# Tags:    <ip>  IP address
#          <failures>  number of failures
#          <time>  unix timestamp of the ban time
# Values:  CMD
```

If would be great if a <banduration> were exposed.

**Comment by sebres** [comment]
> It would be useful if we could pass the ban-time duration value/variable as a tag to the action so that we can communicate this back in any logging we are doing external to f2b.
> In other words, currently ...

Well, this list is incomplete... We have successive extended the tags - [for 0.10th version](https://github.com/fail2ban/fail2ban/blob/c8059bf9b35a167ad7bd4579f83495f9dda50c79/fail2ban/server/actions.py#L366-L384) resp. [for 0.11th version](https://github.com/fail2ban/fail2ban/blob/6ef69b48cad9beb2b3106f7bd3701b3434406398/fail2ban/server/actions.py#L377-#L397)

> It would be great if a `<banduration>` was exposed.

I guess you mean `<bantime>` - if so, this is already there.
Just note that in a 0.11-th if the `bantime.increment` feature is involved, it is a bit complicated. Because this prolongation is an asynchronous process, the `actionban` can get initial values of `<bantime>` and `<bancount>`. Correct (increased) values will be supplied to `actionprolong` command, which is called hereafter for all tickets of recidive (known as "bad") IPs.

**Comment by mtompkins** [comment]
Thank you for this clarification. I think some language that indicates if bantime = when it was banned vs. banned duration might be something to consider.

**Pull request merged**
