### PR TITLE
Add support to Proxmox Web GUI

### PR DESCRIPTION
**Pull request by Jose-Derecho**
Ban users on Proxmox Web GUI

Line matching on /var/log/daemon.log:
```
Mar  8 09:37:44 F39068A pvedaemon[12021]: authentication failure; rhost=212.106.229.105 user=root@pam msg=Authentication failure
```

### CODE REVIEW

**Comment by Neustradamus** [comment]
@sebres: Have you planned to merge it?

**Comment by Fantu** [comment]
I also added manually to proxmox 8 servers I manage, except the difference that I use `backend = systemd` instead of the daemon.log

**Comment by sebres** [comment]
rebased/merged

**Comment by Neustradamus** [comment]
@sebres: Good news, thanks!

**Pull request closed without merging**
