### PR TITLE
Add filter variable __pam_auth

### PR DESCRIPTION
**Pull request by opoplawski**
Add filter variable __pam_auth to allow easier changing of pam auth backend.

This is an initial step for fixing issue #928 - would still be nice to auto set this.

### CODE REVIEW

**Comment by yarikoptic** [comment]
shouldn't we just list them all (```pam_(unix|sss)```) or just allow ```pam_\S+```?

**Comment by sebres** [comment]
Yep, `pam_\S+` would be indeed good also.
But why not both: 
- we can use everywhere in filter a `%(__pam_auth)s`;
- and in `config/filter.d/common.conf` default value can be `__pam_auth  = pam_\S+`

So if needed, everyone is capable to specify jail own pam-suffix just with overwriting of `%(__pam_auth)s`;

**Comment by opoplawski** [comment]
Please read issue #928 - the problem is that for network users pam_unix will always return an auth failure, which would then trigger a ban.

**Comment by yarikoptic** [comment]
@opoplawski ah -- right.  ok then.. just add a ChangeLog for that .

Not sure how 'autoset'ing could work here though, so why not just to consider #928 closed by this one?

**Comment by opoplawski** [comment]
Here's my idea for auto generating (which could be a separate issue if we want to pursue it):

You don't want to key off of errors in any earlier entries in /etc/nssswitch.conf as they may be superseded by later modules.  You probably just want the last one.  I suspect 99% of entries are like:
````passwd: files sss````
or
````passwd: files ldap```` where you only want to key off of the last entry.  If __pam_auth were set to pam_sss or pam_ldap by default in these cases, I think you would cover most cases automatically.  "files" would be special case and would result in "pam_unix".

**Comment by yarikoptic** [comment]
@opoplawski   sorry -- I am still a bit missing how we would automate that at fail2ban level

**Pull request merged**
