### PR TITLE
Separate php-url-fopen logpath by newline

### PR DESCRIPTION
**Pull request by opoplawski**
Reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1169026 and apparently mentioned on the users list

### CODE REVIEW

**Comment by luk911** [comment]
not working on CentOS 6 with fail2ban-0.9.2-1.el6

**Comment by luk911** [comment]
I try 
[suhosin]
enabled         = true
port            = http,https
filter          = suhosin
action          = iptables-multiport[name=suhosin, port="http,https"]
logpath         = /var/log/lighttpd/error.log
maxretry        = 1

and bug still there

**Comment by luk911** [comment]
i change default section
[suhosin]

port    = http,https
#logpath = %(suhosin_log)s
logpath = /var/log/lighttpd/error.log

and bug gona :)

**Comment by yarikoptic** [comment]
what does it have to do with the original issue @luk911 ?

**Comment by luk911** [comment]
same allert

**Comment by infografik** [comment]
Always check the log file /var/log/fail2ban.log, everything there is, for example:

fail2ban.transmitter [xxxxx]: WARNING Command [ 'set', 'Suhosin', 'addlogpath', '/ var / log / messages', '/var/log/lighttpd/error.log'] has failed. Received ValueError ("File option must be 'head' or 'tail' ')

for %(suhosin_log)s in jail.conf

**Pull request merged**
