### PR TITLE
Updated postfix-sasl.conf failregex

### PR DESCRIPTION
**Pull request by agentmoller001**

### CODE REVIEW

**Comment by yarikoptic** [comment]
That (?i) should have made it already case insensitive. What is the log line it was not catching?

**Comment by agentmoller001** [comment]
Feb 28 04:43:19 server1 postfix/smtpd[1177]: warning:
unknown[xxx.xxx.xxx.xxx]: SASL Login authentication failed: UGFzc3dvcmQ6

**Comment by yarikoptic** [comment]
matches for me just fine:
```
$> PYTHONPATH=$PWD bin/fail2ban-regex "Feb 28 04:43:19 server1 postfix/smtpd[1177]: warning: HOSTNAME[1.1.1.1]: SASL Login authentication failed: UGFzc3dvcmQ6" config/filter.d/postfix-sasl.conf                                                                                                                                                  

Running tests
=============

Use   failregex filter file : postfix-sasl, basedir: config
Use      single line : Feb 28 04:43:19 server1 postfix/smtpd[1177]: warni...


Results
=======

Failregex: 1 total
|-  #) [# of hits] regular expression
|   1) [1] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?postfix/(submission/)?smtp(d|s)(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix/(submission/)?smtp(d|s)(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*warning: [-._\w]+\[<HOST>\]: SASL ((?i)LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/:]*={0,2})?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [1] (?:DAY )?MON Day 24hour:Minute:Second(?:\.Microseconds)?(?: Year)?
`-

Lines: 1 lines, 0 ignored, 1 matched, 0 missed
[processed in 0.00 sec]

```
may be the catch in what you have hidden from us (IP/hostname)?

**Comment by yarikoptic** [comment]
anyways -- I consider this PR incorrect since ignoring case is within the failregex... if anything it is a new issue, please open one first and provide all relevant information it would ask

**Comment by agentmoller001** [comment]
Here are two exact log entries from mail.warn:
Feb 28 02:56:53 server1 postfix/smtpd[19506]: warning: unknown[185.103.252.12]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
Feb 28 03:07:20 server1 postfix/smtpd[19506]: warning: unknown[69.11.247.146]: SASL Login authentication failed: UGFzc3dvcmQ6

Here's the proof:

root@server1:/# fail2ban-regex /var/log/mail.warn /etc/fail2ban/filter.d/postfix-sasl.conf

Running tests
=============
Use   failregex file : /etc/fail2ban/filter.d/postfix-sasl.conf
Use         log file : /var/log/mail.warn

Results
=======
Failregex: 1158 total
|-  #) [# of hits] regular expression
|   1) [1158] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [3435] MONTH Day Hour:Minute:Second
`-

Lines: 3435 lines, 0 ignored, 1158 matched, 2277 missed
Missed line(s): too many to print.  Use --print-all-missed to print all 2277 lines
root@server1:/# nano /etc/fail2ban/filter.d/postfix-sasl.conf
root@server1:/# fail2ban-regex /var/log/mail.warn /etc/fail2ban/filter.d/postfix-sasl.conf

Running tests
=============
Use   failregex file : /etc/fail2ban/filter.d/postfix-sasl.conf
Use         log file : /var/log/mail.warn

Results
=======
Failregex: 1471 total
|-  #) [# of hits] regular expression
|   1) [1471] ^\s*(<[^.]+\.[^.]+>)?\s*(?:\S+ )?(?:kernel: \[ *\d+\.\d+\] )?(?:@vserver_\S+ )?(?:(?:\[\d+\])?:\s+[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?|[\[\(]?postfix/smtpd(?:\(\S+\))?[\]\)]?:?(?:\[\d+\])?:?)?\s(?:\[ID \d+ \S+\])?\s*warning: [-._\w]+\[<HOST>\]: SASL (?:LOGIN|Login|PLAIN|(?:CRAM|DIGEST)-MD5) authentication failed(: [ A-Za-z0-9+/]*={0,2})?\s*$
`-

Ignoreregex: 0 total

Date template hits:
|- [# of hits] date format
|  [3435] MONTH Day Hour:Minute:Second
`-

Lines: 3435 lines, 0 ignored, 1471 matched, 1964 missed
Missed line(s): too many to print.  Use --print-all-missed to print all 1964 lines

**Comment by yarikoptic** [comment]
>    Failregex: 1158 total
>    |- #) [# of hits] regular expression
>    | 1) [1158] ^\s(<[^.]+.[^.]+>)?\s(?:\S+ )?(?:kernel: [ \d+.\d+]
>    )?(?:@vserver_\S+
>    )?(?:(?:[\d+])?:\s+[[(]?postfix/smtpd(?:(\S+))?[])]?:?|[[(]?postfix/smtpd(?:(\S+))?[])]?:?(?:[\d+])?:?)?\s(?:[ID
>    \d+ \S+])?\swarning: [-._\w]+[]: SASL (?:LOGIN|PLAIN|(?:CRAM|DIGEST)-MD5)

so you are using old fail2ban here?  there is no case insensitive flag
in above 

if you went through the checklist for an issue -- you might have discovered that earlier ;)

**Pull request closed without merging**
