### PR TITLE
Suggested changes for PR 1116 - unifying camelCasing

### PR DESCRIPTION
**Pull request by yarikoptic**
probably introduction of '_', more pythonic, syntax into method names is my sin.  So I have decided to address it at least partially at least here -- let's stick to camelCase which we do use much more in the code base

descriptive variables in loops are much more preferable, thus did that too

### CODE REVIEW

**Comment by sebres** [comment]
Thx, but I should merge it hereafter to all my branches... includes 716.
But, OK - still please, please! no more changes if not significant matter.

**Comment by sebres** [comment]
rebased because of stupid github cross-reference branching...

**Comment by sebres** [comment]
@yarikoptic If next time you will push to this origin (as new branch), instead of your own, I can merge it easy, possibly with fast forward.
Rebased, because I need this branch so clean as possible (without other merges) to easy merge resp. rebase it later in my development strand.

**Comment by yarikoptic** [comment]
1. just add my repository as a remote and you would be able to merge from there as easily.  Actually I would prefer to keep this repository clean of perspective branches, and we should all push perspective changes into ours and request PRs from them.

2. I am afraid you are torturing yourself with undue rebases too much ;)  I thought you have this branch available for merging updates from it into your other feature branches.  Then even if they are present in their own PRs, after this one gets merged, your other PRs would prune changes which would be in the master already.   So far such workflow based on merges worked for me quite well, even though indeed the "git commits tree" with merges might become trickier to interpret or follow.

**Comment by yarikoptic** [comment]
not to mention that git has more difficulty merging branches with lots of rebased cherry-picked commits.

**Comment by sebres** [comment]
> not to mention that git has more difficulty merging branches with lots of rebased cherry-picked commits.

It's definitely not so, because if I have conflict between two "clean" (rebased) branches, it will be possible to resolve that conflict within single pick only (if rebase) or within last merge of it. 
If I have cross-reference branching - I can have this conflict situation on each merge additionally. And if we think about how long my branches live in this project... Oh, nee.

About adding of your origin - I have already 4 active origins (gh-upstream, gh-sebres, my own on my private server, my own 2nd localy) + additionaly 1 passive for release to my networks. Still one - and I will lost my mind :)

**Comment by yarikoptic** [comment]
On Fri, 17 Jul 2015, Serg G. Brester wrote:
>      not to mention that git has more difficulty merging branches with lots
>      of rebased cherry-picked commits.
>    It's definitely not so

;-) and I think that it is so :-P


>     because if I have conflict between two "clean"
>    (rebased) branches, it will be possible to resolve that conflict within
>    single pick only (if rebase) or within last merge of it.

"single pick" alone sounds "dangerous" since it would lead to adopting
one version of the code and abandoning the other one completely, i.e. something
like "git merge -Xtheirs or -Xours" which should be used with extreme caution


>    If I have cross-reference branching - I can have this conflict situation
>    on each merge additionally. 

once resolved -- that conflict would not arise again in subsequent merges.
With constantly rebased branches -- you have those conflicts reoccurring.
This leads to more fragile workflow -- making it preferable to not
introduce fixes in PRs (as you stated).

E.g. that is how we kept fixes originally introduced within 0.8 branch
propagating to master -- just merging 0.8 over and over again, whenever new
fixes were brought there.  And e.g. "git diff master...0.8" and "git log
master 0.8" can be used to identify commits/changes which are still present in
0.8 and were not merged into master.


> And if we think about how long my branches live in this project... Oh, nee

Especially there, rebased branches would indeed give you the conflicts, while
consecutive merges would not lead to reincarnation of dealing with old
conflicts.


>    About adding of your origin - I have already 4 active origins
>    (gh-upstream, gh-sebres, my own on my private server, my own 2nd localy) +
>    additionaly 1 passive for release to my networks. Still one - and I will
>    lost my mind :)

$> git remote | wc -l
185

and I am still sane ;)  Use bash completions for git, consistent
prefixing, and it would help even more ;)

-- 
Yaroslav O. Halchenko, Ph.D.
http://neuro.debian.net http://www.pymvpa.org http://www.fail2ban.org
Research Scientist,            Psychological and Brain Sciences Dept.
Dartmouth College, 419 Moore Hall, Hinman Box 6207, Hanover, NH 03755
Phone: +1 (603) 646-9834                       Fax: +1 (603) 646-1419
WWW:   http://www.linkedin.com/in/yarik

**Pull request merged**
