### PR TITLE
WiP: Replace <HOST> with default host regex

### PR DESCRIPTION
**Pull request by da2x**
Match the regex used in fail2ban/server/failregex.py

### CODE REVIEW

**Comment by yarikoptic** [comment]
could you please elaborate why? or what for?

**Comment by Aeyoun** [comment]
* Sharing the same regex replacement as used elsewhere in Fail2Ban
* Adds IPv6 support

This regex replacer was probably forgotten when IPv6 support was added to `fail2ban/server/failregex.py`.

**Comment by Aeyoun** [comment]
So, don’t merge this. Leaving it open as it should use the same regex as is decided on in #1374.

**Comment by yarikoptic** [comment]
retitled with WiP prefix (for work in progress == do not merge)

**Comment by sebres** [comment]
Fixed in #1715, because of better solution by general tag replacements (we've more tags as `<HOST>` now)

**Pull request closed without merging**
