### PR TITLE
Apache URIs can contain spaces

### PR DESCRIPTION
**Pull request by benrubson**
Hello,

This PR solves #1644.

_Apache URIs can contain spaces.
In this case, log lines are not caught by Fail2Ban._

Ben

### CODE REVIEW

**Comment by sebres** [comment]
Although I like it, but because there are some paranoid of us... :)

@yarikoptic Your decision?

Secondly, I'll appreciate that `user \S*` will be replaced with `\S+`. 
We talked already about it:
> For example if by the handshake, before the client send authentication data, the web-server (or application) will produce 401 (and failure in log in sense of fail2ban), it is also counted. So the client should make `maxretry` of such "failures" - it goes banned.
> This question is thus not really answerable as long as too few info... But rather - no, because makes no sense.

**Comment by benrubson** [comment]
Thank you for your feedback @sebres.
Regarding `\S+` instead of `S*` for user, there are some Apache tests inside `fail2ban/tests/files/logs/apache-auth` that look for an empty user.
This is why I kept the `\S*` version :)

**Comment by benrubson** [comment]
@yarikoptic may we have your feedback regarding this PR please ?

And what about the 3 remaining untouched rules, any idea to shorten them ?

Many thx 👍

**Comment by sebres** [comment]
I've ported it to newest 0.10 (with `prefregex`), with little review and clean-up by the way.
Will merge if test cases passed.
Thanks!

**Comment by benrubson** [comment]
Thank you very much @sebres 👍 
There are still 2 rules containing `(, referer: \S+)?`, you did not manage to get ride of this ?
Thx !

**Comment by sebres** [comment]
Done, see 6dfd080

**Comment by benrubson** [comment]
Perfect thx 👍

**Comment by sebres** [comment]
small amend in 507034c5be77c7894e2eee8afc2ce4ea84002674: joined some similar expressions

**Pull request merged**
