### PR TITLE
Fixes abuseipdb curl cypher error and comment $f2bV_matches

### PR DESCRIPTION
**Pull request by mercurytoxic**
Fixes issue #2044 curl cypher error  
and used #2039 to fix comment=<matches> resulting in abuseipdb.com only showing $f2bV_matches on the comment line.

### CODE REVIEW

**Comment by sebres** [comment]
Thanks for PR!
Rebased to current 0.10 and added changelog entry.

**Comment by sebres** [comment]
Thus merged in 0.10 and 0.11.

**Comment by stratege1401** [comment]
does that mean this is also fixed in the apt-get packages version (0.10.2-1) for debian ?

**Comment by sebres** [comment]
> does that mean this is also fixed in the apt-get packages version (0.10.2-1) for debian ?

Nope, 
if you'll look at commit https://github.com/fail2ban/fail2ban/pull/2101/commits/d9525ad3aafb3a3a3387e402fcb965a730cf6a97 you'll see versions `0.10.3.1`, `0.10.3` only.

**Comment by stratege1401** [comment]
ok, any clue about date for apt-get packages updates ??

**Comment by sebres** [comment]
No idea...
@yarikoptic ?

In between you could simply update your /etc/fail2ban/action.d/abuseipdb.conf manually, like in commit https://github.com/fail2ban/fail2ban/commit/fc76ccf19218f7eb14afcbf916fe47c3c9ccaa95

**Pull request merged**
