### PR TITLE
Added regex for LDAP authentication failures

### LINKED ISSUE #1291: dovecot ldap regex
There's a note in the dovecot filter that the supplied regexs don't catch ldap queries (which they don't).

The following regex seems to do the job though: please add to the package when you have a spare moment!

```
^%(__prefix_line)s(auth|auth-worker\(\d+\)): Info: ldap\(\S*,<HOST>,\S*\): invalid credentials$
```

### PR DESCRIPTION
**Pull request by theDogOfPavlov**
resolves #1291

Mar 23 06:10:52 auth: Info: ldap(dog,52.37.139.121,<jhgsdfhgjSDF3>): invalid credentials

### CODE REVIEW

**Comment by theDogOfPavlov** [comment]
Please merge

**Comment by sebres** [comment]
Each failregex expression (line) should have at least one test case, so please extend <a href="https://github.com/fail2ban/fail2ban/blob/master/fail2ban/tests/files/logs/dovecot">tests/files/logs/dovecot</a> with corresponding lines (json with match true and example line after it)...

You can test if it has success with following command:
```
PYTHONPATH=. bin/fail2ban-testcases FilterSamplesRegex
```

BTW. I miss changelog entry also...

**Comment by theDogOfPavlov** [comment]
Ah, sorry, missed that. N00b error. ;)

I'll run up the test cases etc when I get a few spare minutes this week.

**Comment by theDogOfPavlov** [comment]
ok, added in the tests and updated the changelog. Should be ready to commit...

**Comment by sebres** [comment]
I don't really like such not exact expressions, compare `\(\S*,<HOST>,\S*\)` and `\([^\s,]*,<HOST>,[^\s\)]*\)`...
But we have already many of which... So merge now

**Comment by theDogOfPavlov** [comment]
no longer required...

**Pull request merged**
