### PR TITLE
Display ChangeLog as a Markdown document

### PR DESCRIPTION
**Pull request by szepeviktor**
Docs: https://github.com/github/linguist/blob/master/docs/overrides.md

Soon should look like https://github.com/szepeviktor/fail2ban/blob/master/ChangeLog.md
For GitHub 😍

### CODE REVIEW

**Comment by sebres** [comment]
Looks like something became broken hereafter.
[ChangeLog](https://github.com/fail2ban/fail2ban/blob/master/ChangeLog) looks completely as plaintext without line feeds now.

**Comment by szepeviktor** [comment]
I see.
Would you merge this PR?

**Comment by szepeviktor** [comment]
That comment was a mistake. Sorry.

**Comment by sebres** [comment]
Referenced issue https://github.com/github/linguist/issues/5799

**Pull request merged**
