### PR TITLE
add managesieve and submission support in dovecot filter

### PR DESCRIPTION
**Pull request by mateusz834**
Fix issue: https://github.com/fail2ban/fail2ban/issues/2794

### CODE REVIEW

**Comment by yitzhaq** [comment]
Heh, I was just about to submit a PR for exactly this, but I see this is already in the queue. Although, could you update it to also include `submission` as well as `managesieve`, and save me the trouble of having to file a separate PR just for that?
Thanks!

**Comment by yitzhaq** [comment]
Oh, and one more change is needed, sorry.

`^(?:Aborted login|Disconnected)` -> `^(?:Aborted login|Disconnected|Remote closed connection)`

**Comment by sebres** [comment]
Please always provide an excerpt with log-messages affected by the PR (in ideal case full log-excerpt of single attempt).

**Comment by yitzhaq** [comment]
Anonymized log excerpts for submission protocol follow:

Aug 10 14:45:51 server dovecot: submission-login: Client has quit the connection (auth failed, 1 attempts in 3 secs): user=<username>, method=LOGIN, rip=0.0.0.0, lip=0.0.0.0
Aug 10 15:12:47 server dovecot: submission-login: Remote closed connection (auth failed, 1 attempts in 3 secs): user=<username>, method=PLAIN, rip=0.0.0.0, lip=0.0.0.0

I don't get enough attempts against managesieve to have relevant log entries for that yet, but I can confirm that with the above proposed changes to the PR, these log entries are successfully caught for submission. I assume they should work the same for managesieve, unless Dovecot uses even more alternative phrasing for that protocol. I'll do some testing to see if I can trigger a warning or two.

**Comment by yitzhaq** [comment]
This one is now also caught, so with the above proposed changes this should work for both managesieve and submission:

`Aug 10 15:33:53 server dovecot: managesieve-login: Disconnected: Too many invalid commands. (auth failed, 1 attempts in 2 secs): user=<username>, method=PLAIN, rip=0.0.0.0, lip=0.0.0.0, TLS, TLSv1.3 with cipher TLS_CHACHA20_POLY1305_SHA256 (256/256 bits)`

Let me know if you want me to submit a new PR including both managesieve and submission changes, or if we wait for this one to be updated to include them.

**Comment by mateusz834** [comment]
Just added new commit.

**Comment by yitzhaq** [comment]
Looks ready for merging as far as I'm concerned, maybe with a retitle first to include submission (if possible).

**Comment by sebres** [comment]
As I wrote "full excerpt", I mean an excerpt with all messages of single failed authentication attempt.

So an amend with `|Remote closed connection|Client has quit the connection` may affect a counting of failures (so for example would earlier exceed `maxretry`).
For instance if some session looks like:
```
Aug 10 14:45:51 server dovecot[8935]: managesieve-login: Aborted login (auth failed, 1 attempts in 19 secs): user=<username>, method=PLAIN, rip=192.0.2.200, lip=192.0.2.100, TLS, session=<7nJZQNar0nG8kyRt>
Aug 10 14:45:51 server dovecot[8935]: managesieve-login: Client has quit the connection (auth failed, 1 attempts in 3 secs): user=<username>, method=LOGIN, rip=192.0.2.200, lip=192.0.2.100
```
it would count the same failure twice (thus by `maxretry = 5` would ban already after 3 failures like this).

This may be acceptable for aggressive mode, but not for normal mode.

**Comment by mateusz834** [comment]
So what do you think. Should i delete this **"|Remote closed connection|Client has quit the connection"**, in both or only in normal mode?

**Comment by sebres** [comment]
No, or dunno either...
Rather I am interested in seeing the log excerpt (or whether such scenario I provided above as example is possible).
If don't, then the change is legitimate and you can retain that for all modes.

**Comment by yitzhaq** [comment]
Looks pretty full to me?

```
% grep 183.136.134.133 /var/log/mail.log
Aug  9 03:17:18 server dovecot: submission-login: Client has quit the connection (auth failed, 1 attempts in 2 secs): user=<user1, method=LOGIN, rip=183.136.134.133, lip=0.0.0.0
Aug  9 12:11:40 server dovecot: submission-login: Client has quit the connection (auth failed, 1 attempts in 3 secs): user=<user2>, method=LOGIN, rip=183.136.134.133, lip=0.0.0.0
Aug 10 14:45:51 server dovecot: submission-login: Client has quit the connection (auth failed, 1 attempts in 3 secs): user=<user3>, method=LOGIN, rip=183.136.134.133, lip=0.0.0.0
Aug 10 17:40:38 server dovecot: submission-login: Client has quit the connection (auth failed, 1 attempts in 4 secs): user=<user2>, method=LOGIN, rip=183.136.134.133, lip=0.0.0.0
```


```
% grep 92.55.237.16 /var/log/mail.log
Aug  9 03:53:52 server dovecot: submission-login: Remote closed connection (auth failed, 1 attempts in 2 secs): user=<user4>, method=PLAIN, rip=92.55.237.169, lip=0.0.0.0
Aug 10 14:17:43 server dovecot: submission-login: Remote closed connection (auth failed, 1 attempts in 2 secs): user=<user5>, method=PLAIN, rip=92.55.237.16, lip=0.0.0.0
Aug 11 00:40:54 server dovecot: submission-login: Remote closed connection (auth failed, 1 attempts in 3 secs): user=<user6>, method=PLAIN, rip=92.55.237.16, lip=0.0.0.0
```

```
% grep 0.0.0.0 /var/log/mail.log | grep managesieve
Aug 10 15:30:43 server dovecot: managesieve-login: Login: user=<myself>, method=PLAIN, rip=0.0.0.0, lip=0.0.0.0, mpid=20415, TLS, TLSv1.3 with cipher TLS_CHACHA20_POLY1305_SHA256 (256/256 bits)
Aug 10 15:33:53 server dovecot: managesieve-login: Disconnected: Too many invalid commands. (auth failed, 1 attempts in 2 secs): user=<myself>, method=PLAIN, rip=0.0.0.0, lip=0.0.0.0, TLS, TLSv1.3 with cipher TLS_CHACHA20_POLY1305_SHA256 (256/256 bits)
Aug 10 15:41:58 server dovecot: managesieve-login: Disconnected: Too many invalid commands. (auth failed, 1 attempts in 2 secs): user=<myself>, method=PLAIN, rip=0.0.0.0, lip=0.0.0.0, TLS, TLSv1.3 with cipher TLS_CHACHA20_POLY1305_SHA256 (256/256 bits)
```

(I only fully anonymized the last one, as I didn't have real examples to dig out other than my own testing. I don't really care about the anonymity of abusers, though.)

This wording seems to be specific to submission:

```
% egrep -c '(Client has quit the connection|Remote closed connection)' /var/log/mail.log                   
8882
% egrep '(Client has quit the connection|Remote closed connection)' /var/log/mail.log | grep -vc submission
0
```

**Pull request merged**
