### PR TITLE
Merge 0.8 master

### PR DESCRIPTION
**Pull request by kwirk**
A proposed merge of _0.8_ branch into _master_, ready for a _0.9.1_ release.

### CODE REVIEW

**Comment by yarikoptic** [comment]
eh -- we should get back to this one @fail2ban/developers  ;-)

**Comment by leeclemens** [comment]
Seems at least one of these commits has already been merged, (`testLogTargetSYSLOG` https://github.com/kwirk/fail2ban/commit/09b2016c050defae8f087166fcca51deff7064f5 75325da09091f3ae800a2efbcde1a016617e5f1a).  Maybe this should be rebased before considered again?

**Comment by yarikoptic** [comment]
Merge can't be rebased ;-)  someone just needs to see what leftout changes which we haven't picked up yet from 0.8 are about and either we need them

**Comment by sebres** [comment]
Too different, if something still needed, should be anyway manually rebased (e. g. resolved into new branch).

**Pull request closed without merging**
