### PR TITLE
filter.d/sshd.conf: fixed ddos-mode regex (extended with port)

### PR DESCRIPTION
**Pull request by MatthieuBarbu**
in line 58, rule don't match with "%(__suff)s" but work fine if I replace with "%(__on_port_opt)s"
Debian 9 stretch : fail2ban 0.10.3

### CODE REVIEW

**Comment by sebres** [comment]
Could you provide an excerpt from log-file affected by this issue?

**Comment by MatthieuBarbu** [comment]
Hi Sergey,


Mar  2 17:45:59 dev sshd[8760]: Did not receive identification string from 183.136.188.116 port 55565
Mar  2 17:57:58 dev sshd[8776]: Received disconnect from 159.65.232.26 port 58846:11: Bye Bye [preauth]
Mar  2 17:57:58 dev sshd[8776]: Disconnected from 159.65.232.26 port 58846 [preauth]
Mar  2 17:57:59 dev sshd[8778]: Received disconnect from 159.65.232.26 port 59240:11: Bye Bye [preauth]
Mar  2 17:57:59 dev sshd[8778]: Disconnected from 159.65.232.26 port 59240 [preauth]
Mar  2 18:07:39 dev sshd[8782]: Did not receive identification string from 162.254.158.130 port 35836


the first line don't matched, I was modified sshd.conf and the last line matched

Best regards,
thanks for your job :)

Matthieu

**Comment by sebres** [comment]
It looks indeed it was again refactored (openssh commit 5f2e4df88d4803fc8ec59ec53629105e23ce625e), e. g.:
https://github.com/openssh/openssh-portable/blob/95767262caa6692eff1e1565be1f5cb297949a89/sshd.c#L452-L453
Thus accepted (I'll still make it more backwards compatible).

**Comment by MatthieuBarbu** [comment]
You can see in my log, this line,

Mar 2 17:57:58 dev sshd[8776]: Received disconnect from 159.65.232.26 port 58846:11: Bye Bye [preauth]

the port number is present too, so this rule line 52 (same line with one space too many before 11) don't work for the same reason, i see that after my first PR

would you like an other new PR for that?

**Comment by sebres** [comment]
Good catch, thanks for the attention...

> would you like an other new PR for that?

Nope. I'll extend it here.
Thanks, again.

**Comment by sebres** [comment]
Yeah, this one can be found here:
https://github.com/openssh/openssh-portable/blob/748dd8e5de332b24c40f4b3bbedb902acb048c98/packet.c#L1718-#L1719
So fixed too in commit above.

**Comment by MatthieuBarbu** [comment]
It’s my pleasure :)

If I find other thing, I'll be sure to open new PR.

fail2ban is good project, if I can contribute I'll do it ;)

**Pull request merged**
