### PR TITLE
An IP address has a PTR record

### PR DESCRIPTION
**Pull request by szepeviktor**
In sendmail-geoip-lines action

### CODE REVIEW

**Comment by szepeviktor** [comment]
Should it be against 0.9?

**Comment by szepeviktor** [comment]
Would it be possible to merge this one?

**Comment by sebres** [comment]
I've made a little bit better solution (see #1705).
For older version (v.0.9.x) we can use this one.

**Comment by szepeviktor** [comment]
@sebres Thank you.

If there are multiple PTR record which one will get displayed?

**Comment by sebres** [comment]
> If there are multiple PTR records which one will get displayed?

Currently this will return the first only. Of course we can change it to return a list, or still one tag `<ip-hosts>` that in opposition to `<ip-host>` returns a list.
But multiple PTR records (i. e. reverse-DNS) are not recommended (and too rare in the practice).

BTW In opposition to `host -t PTR ...` the new tag `<ip-host>` returns only available host name. I. e. no arpa reversed address (for this purpose use another tag `<ip-rev>`):
```bash
$ host -t PTR "4.4.4.4"
Host 4.4.4.4.in-addr.arpa. not found: 3(NXDOMAIN)

$ # ip-host:
$ fail2ban-python -c "from fail2ban.server.ipdns import IPAddr; print(IPAddr('4.4.4.4').getHost())"
None

$ # ip-rev:
$ fail2ban-python -c "from fail2ban.server.ipdns import IPAddr; print(IPAddr('4.4.4.4').getPTR())"
4.4.4.4.in-addr.arpa.
```

**Pull request closed without merging**
